spring:
  application:
    name: gforo
  datasource:
    url: jdbc:mysql://localhost:3306/gforo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080


# logback

#logging:
#  level:
#    root: debug
#  file:
#    path: /Users/gabrielgao/Desktop/my_practices/log/gforo.log
