spring:
  application:
    name: gforo
  datasource:
    url: jdbc:mysql://localhost:3306/gforo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    username: gabrillo177@gmail.com
    password: daoikogzxbbmqflr
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

frontend:
    url: http://localhost:5173


# logback

#logging:
#  level:
#    root: debug
#  file:
#    path: /Users/gabrielgao/Desktop/my_practices/log/gforo.log

